SolidOS/solid-ui

lib/acl-control.js

Fixes all JS Standard warnings for file :
lib/acl-control.js
Confirmed as whitespace only:
git diff -w

Whitespace only changes to remove JS Standard warnings

---

lib/matrix.js
lib/table.js
lib/utils.js
lib/widgets.js

Companion PR to https://github.com/linkeddata/rdflib.js/pull/142

Update termType to RDFJS spec

---

src/signin.js

solid-auth-client supports a .well-known popup URI as a default, so it is not necessary to specify this popup.
Moreover, if we do specify this popup URI, we risk running into https://github.com/solid/solid-auth-client/issues/54
Also, with the current implementation, Mashlib crashes if `$SOLID_GLOBAL_config` is not set.

Use default popup URI

---

.gitignore

Just a small fix to make setup a bit easier for users of JetBrains IDEs (myself included). Tried adding [suggestiono of .gitignore from gitignore.io](https://www.gitignore.io/api/osx,node,code,windows,jetbrains), which leaves some .idea-files to be inserted, but concluded that's probably just going to be annoying for non-JetBrains developers.

Ignoring JetBrains IDE files

---

src/widgets/index.js

The regex for phones is still not great, but we'll leave it at this for now until we have a more thorough change of the profile pane

Fixing bug in regex for phone field

---

src/widgets/index.js

obj.uri might be undefined, which will output "undefined" in field values since empty string are falsish
This should fix https://github.com/solid/solid-panes/issues/118

Need to set an empty string as last value possible

---

src/create.js

This will allow us to continue using the mintClass attribute, but data browser will automatically handle multiple panes creating the same class

Will prepend the name of the pane if multiple panes create same class

---

src/widgets/dragAndDrop.js

The handling of ACL for root failed because the URI to PUT the file to contained an extra slash (e.g. `https://test.com//foo.txt` instead of `https://test.com/foo.txt`). This was an error that also happens when trying to upload files elsewhere, but it was allowed then.
This should fix https://github.com/solid/solid-panes/issues/143

Only adding a slash to destUri if folderName does not already have it

---

src/widgets/forms.js

If the BooleanField in the given resource is not set, the tristate
logic would set it to false by default. This commit changes that to
differentiate between the value that is shown (false), and the
value that's actually present on the web.
These changes were made as per Tim's instructions. They came up when working on https://github.com/solid/solid-panes/issues/144.

Do not prefill a value for a checkbox

---

Documentation/forms-intro.html

* bunches of typos
* some grammar and punctuation

clean up forms-intro.html

---

src/acl.js

This fixes https://github.com/solid/solid-ui/issues/99
The test was there to prohibit calls on https://, as we had a recursive call that would do that. But this also prohibits call that would check for the root ACLs, so need to make it a bit less strict.

Allow for creation of ACL resources on folders directly under root

---

src/widgets/forms.js

Tim has said in a call that it's weird that this line is there in the first place and should be removed, so I guess this doesn't need another review from him.
Fixes #105.

Don't store a field's default value in the store

---

src/acl-control.js

This checks whether pathname indicates that the target is root, or whether the root ACL itself states that the target is root.
Going to create a PR for NSS as well that adds `<.> a sp:Storage.` as default for all _new_ root ACLs.

Prevent users from deleting their root ACLs

---

src/signin.js

Adding methods `filterAvailablePanes` (returns which panes a user should see based on their roles) and `getUserRoles` (returns roles for a user).
This is part of fixing https://github.com/solid/solid-panes/issues/167

Added methods to filter panes based on user roles (Developer/PowerUser)

---

src/tabs.js

By providing option onClose, tabs are extended with an extra, unstyled tab that contains a cancelButton. Once clicked it will call the given onClose-method.
This is needed for providing the cancelButton for the global dashboard.
Part of fix for https://github.com/solid/solid-panes/issues/154

Adds optional cancelButton to end of tabs

---

src/signin.js
src/widgets/buttons.js

findImage used to be a private function in UI.widgets.buttons.setImage, but the logic can be reused other places, so I've tried to extract the logic so that it becomes a method exposed as UI.authn.findProfileImage.
Partially fixes https://github.com/solid/solid-panes/issues/169

Extracted findProfileImage from findImage in setImage

---

src/acl-control.js

I'm not sure what "default" is supposed to mean, but stepping
through in the debugger showed that the property had an `-s`
appended, I presume that's what it should be?
The code has been there for three years though, so not sure
whether it's even supposed to be doing something?
(Also a +1 for #69, which would have caught this.)
Since solid-ui has no test tooling set up yet, this PR does not include tests.

Look for `doingDefaults` rather than `doingDefault`

---

package-lock.json
src/signin.js

Could happen when a data browser on domain A does not have access to a Pod on domain B.
Reusing existing functionality to load preferences.
Should fix https://github.com/solid/solid-panes/issues/185

getUserRoles will return an empty array if it fails to load preferences

---

src/acl-control.js

Should fix https://github.com/solid/solid-panes/issues/193

Reintroducing use of byCombo

---

package.json

This fixes an issue created by https://github.com/solid/solid-ui/pull/127, where the index (the only typescript file) is not compiled to javascript since babel doesn't recognize its file extension.
The missing `lib/index.js` file causes `module not found` exceptions in downstream projects

Include ts files in babel builds

---

.gitignore
package.json
src/index.ts
timestamp.sh

See https://github.com/solid/solid-panes/pull/201 for proposed changes

Adding versionInfo + standardizing scripts

---

src/create.js

While migrating create module to TypeScript, I realized that I introduced a bug when introducing the data browser context earlier. This is a fix for that.

Fixing a bug in create module

---

.eslintignore
Documentation/form-ecosystem.html
Documentation/forms-intro.html
README.md
package-lock.json
package.json
src/acl/acl-control.ts
src/create.js
src/style.js
src/utils.js
src/widgets/buttons.js
src/widgets/forms.js

Add ordered option to Multiple field in forms

---

.babelrc
package-lock.json
package.json
src/acl/access-controller.ts
src/acl/access-groups.ts
src/acl/acl-control.ts
src/acl/acl.ts
src/acl/add-agent-buttons.ts
src/acl/styles.ts
src/acl/types.ts
src/jss/index.ts
src/widgets/buttons.js

Is now split into AccessController, AccessGroups, and AddAgentButtons. All methods that are related to DOM manipulation are prefixed `render` - the rest deals with data manipulation and state handling. Further, no non-`render`-methods should call on any `render`-methods.
This (I think) makes the code easier to read and maintain.
Have also added JSS to showcase how dynamic CSS can work. (Is not much work to remove if not wanted.)
Fixes https://github.com/solid/solid-ui/issues/121.

Restructured ACLControlBox5 into multiple modules

---

package.json

This pull request will allow windows developers to run npm run build and also npm run test
Solves this issue https://github.com/solid/solid-ui/issues/213

Making Package.json windows compatible

---

jest.config.js
jest.config.ts
test/setup.ts

Realized that jest config must have file-extension .js in order to let jest recognize it properly. Cleaned it up a bit and made it so that calls on debug methods are ignored in tests.

Fixing jest config + Ignoring debug methods for tests

---

tsconfig.json

We wanted to get it to build types for `src/`, `test/` and `__mocks__/`, but we also wanted the output to go to lib/index.d.ts and not lib/src/index.d.ts. We got the types to build to lib/index.d.ts but now it only builds `src/`. If someone knows how to make it check the types of `test/` and `__mocks__/` as well, please contribute! :)

Build types

---

.github/workflows/ci.yml

With this change, solid-ui will be automatically published to npm when a version is commited/merged to the main branch.
The other job, that I renamed to npm-publish-build, was already present and published everything to npm using the git slug. With this change we also publish a version without slug as latest npm package, but only when on main branch

publish version to npm on main branch

---

src/acl/access-controller.ts
src/acl/acl.ts

@timbl 
Sharing-pane : setting a specific sharing for file returns a void content, but should return the parent acl without acl:default
This PR resolves the following issue #396 and issue https://github.com/solid/solidcommunity.net/issues/39 : 
I did not succeed to make a test
1. the sharing-pane for file: 
- did not display any default content when clicking on `Set specific sharing` (it is looking for a folder acl with acl:default)
- and should not display the button `Set the sharing of folder contents separately from the sharing for the folder`
2. when adding any type of agent the acl was created with only an acl:Read and user was locked out from the file

Sharing-pane : setting a specific sharing for file should return default acl from parent

---

package-lock.json
src/style.js
src/widgets/buttons.ts
test/unit/utils/label.test.ts
test/unit/widgets/forms/autocomplete/__snapshots__/autocomplete.test.ts.snap

Fix the problem that he delete buttons disappear.

Delete button with check

---

.eslintrc
src/acl/access-controller.ts
src/authn/authn.ts
src/chat/infinite.js
src/chat/thread.js
src/folders.js
src/messageArea.js
src/table.js
src/widgets/buttons.ts
src/widgets/forms.js
src/widgets/forms/autocomplete/autocompleteField.ts
src/widgets/forms/autocomplete/autocompletePicker.ts
src/widgets/index.js
test/unit/widgets/buttons/iconLink.test.ts
test/unit/widgets/forms/autocomplete/__snapshots__/autocomplete.test.ts.snap
test/unit/widgets/forms/index.test.ts

Other Test and Linter Fixes:
- Mashlib (https://github.com/solid/mashlib/pull/121)
- Solid-Panes (https://github.com/solid/solid-panes/pull/296)
- Solid-UI (https://github.com/solid/solid-ui/pull/421)
- Rdflib (https://github.com/linkeddata/rdflib.js/pull/511)

Fixed tests and linter

---

test/helpers/setup.ts

I found an elegant way to fix the TextEncoder is not defined issue.

fixed ReferenceError: TextEncoder is not defined

---

src/authn/authn.ts

This PR prefills the text field with the last used IDP (already stored in `localStorage`):

Restore the last used IDP

---

src/authn/authn.ts

use of defaultForNew is deprecated and caused trouble on CSS

use acl:default when writing ACL, not the depcrecated acl:defaultForNew

---

Documentation/forms-intro.html
Documentation/talks/FormsTalk.html
src/style.js
src/widgets/forms.js
src/widgets/forms/basic.ts
src/widgets/forms/fieldParams.ts
test/unit/widgets/forms/basic.test.ts

and some update to the doc. 
Add slide on field properties, and refs to doc at end.

Post talk changes to slides

---

package-lock.json
package.json
src/utils/headerFooterHelpers.ts

this only should only solve part of the issue see https://github.com/solid/solidos/issues/124

load container representation

---

src/login/login.ts

The box.refresh method is one place where we can NOT use authn.currentUser() because what we want to know is not just is the user authorized to be here but are they actually logged in.  So we need authn.authSession.info here.  Otherwise when we are in Data-Kitchen we appear to be logged in to the local host  (so we can access it all) but we aren't actually logged in to it.  However we want the option to login to other places so box.refresh needs to check whether we are actually logged in somewhere else and if not give us the issuer popup.

Support login from Data Kitchen

---

src/widgets/forms.js

Added a check on the following triple : 
```
form ui:options "search-full-store"
```
different solution can also be used like .
```
form ui:search-full-store true
```
Or anything along this idea.

data source option

---

src/chat/chatLogic.js
src/chat/infinite.js

Chat thread proof
