src/ns.js
Fix two semi colons
Fix throw errors instead of strings
Closes #3
=> Conform to JS Standard and throw new Errors closes #3

src/signin.js
@timbl This should fix the `"Cannot load profile undefined : TypeError: webId.doc is not a function"` error you mentioned
=> Fix saveUser() return type

src/create.js, src/messageArea.js, src/pad.js, src/signin.js, src/widgets/index.js
=> Timbl auth - fix bugs and addd consistency in way webid is acquired

package-lock.json, package.json, src/create.js, src/signin.js, src/widgets/index.js
Error handling around prefs
Bug fix in outlinemode link
=> Timbl prefernces

src/infiniteMessageArea.js, src/pad.js, src/preferences.js, src/widgets/dragAndDrop.js, src/widgets/index.js
Bug fixes and tweaks for chat room menu
=> Bug fixes and tweaks for chat room menu

src/infiniteMessageArea.js, src/preferences.js
Better than without.  Issues exist with form checkbox patches not being able to turn a true into a false, but may be a server issue.
=> Use preference values as options in widget

src/infiniteMessageArea.js, src/preferences.js, src/signin.js, src/widgets/dragAndDrop.js, src/widgets/index.js
This is mainly a collection of bugs in things like drag-drop.  It also introduces no functionality used by preferences: a checkbox which can  have 3 states, [yes, no, no opinion] [true|false|null].
=> Timbl tristate and bugfix

package-lock.json, package.json, src/ns.js, src/signin.js
clean up ns, add one, fix context.indexes typo in signin
=> Timbl bugfix2 - signin

package.json
Another small script to make life a bit easier for developers
=> Added watch-script

package-lock.json, src/folders.js, src/signin.js, src/tabs.js, src/widgets/dragAndDrop.js
Where you can currently drop files into your pod, you should also have a file upload button which is pressed gors through the browser-specific file upload process
=> File upload: add fileUploadButtonDiv

src/widgets/index.js
Will remove the initial 409 errors when triples does not exist from before
=> This should make the model correct wrt default values

src/acl-control.js
Still some bugs with the sharing pane, but now it is a bit smoother at least
=> Refresh sharing on creating and deleting specific acl

src/widgets/dragAndDrop.js
Fix typo in file upload button
=> Fix typo addListener

package-lock.json, package.json, src/signin.js, src/widgets/buttons.js, src/widgets/dragAndDrop.js, src/widgets/forms.js
Where the data being viewed by a form is not editable -- either server capability or access control -- this PR disables user input, making a read-only view which is is cleaner, and does not invite editing.
=> Readonly forms

Documentation/forms-intro.html
Add an introduction to using forms
=> Documentation

src/widgets/peoplePicker.js
This is the solid-ui equivalent of https://github.com/solid/mashlib/pull/60.
=> Transition to non-default export for rdflib v1

src/acl-control.js
=> Fix typo: contets -> contents

src/widgets/buttons.js, src/widgets/forms.js
Fix https://github.com/solid/solid-ui/issues/125
=> Exposing buildCheckboxForm and complain to widgets API

.babelrc, package-lock.json, package.json, src/index.ts, tsconfig.json
Fix https://github.com/solid/solid-ui/issues/126
I've only migrated src/index.js to TypeScript to make this change minimal.
It also includes source-maps and builds type definition file as part of `build`-script.
=> A minimal setup to start migrating to TypeScript

src/index.ts, src/widgets/index.js, tsconfig.json
Though I had created this PR earlier, but it's necessary for a lot of the changes that we're doing to solid-panes and mashlib
=> Need to package things a bit different than what I thought before

src/acl-control.js, src/create.js, src/widgets/buttons.js
Related to https://github.com/solid/solid-panes/pull/199
=> Making use of the new context object

src/acl/acl-control.ts, src/authn/authn.ts, src/authn/index.ts, src/authn/types.ts, src/chat/bookmarks.js, src/chat/infinite.js, src/chat/message.js, src/chat/messageTools.js, src/chat/thread.js, src/create.js, src/index.ts, src/messageArea.js, src/pad.js, src/preferences.js, tsconfig.json, typings/solid-auth-tls/index.d.ts
Gave migrating authn module to TypeScript a go.
This builds upon the work in https://github.com/solid/solid-ui/pull/166.
=> Migrate authn

src/authn/authn.ts
* fix typos
* improve readability and English of various human-directed text blocks
* change `makeIndexIfNecesary` function to `makeIndexIfNecessary` (added missing `s`)
=> Variously update authn.ts

src/tabs.js, src/test/test-tabs.html
ooops left off the CSS on the nav/ul
=> Fix flex  direction of ul

__mocks__/rdflib.ts, src/acl/acl.ts, test/unit/acl/access-controller.test.ts, test/unit/acl/access-groups.test.ts, test/unit/acl/acl.test.ts, test/unit/acl/add-agent-buttons.test.ts, test/unit/chat/message.test.ts, test/unit/chat/messageTools.test.ts, test/unit/helpers/instantiateAccessController.ts, test/unit/helpers/instantiateAccessGroups.ts, test/unit/store.test.ts, test/unit/widgets/forms.test.ts
Will try to get branch coverage and API documentation of `src/acl/` to 100%.
Starting from 13% for the folder average (with a 0 for `add-agent-buttons.ts`, somehow?):
=> Small ACL cleanup

examples/notepad/index.html, src/pad.js
Reduced scope of #206 to just its core business.
=> Add notepadToHTML function

Documentation/developers/testing_README.md, __mocks__/solid-auth-client.ts, jest.config.ts, src/widgets/dragAndDrop.js, src/widgets/peoplePicker.js, test/unit/widgets/dragAndDrop.test.ts, test/unit/widgets/peoplePicker.test.ts
Would you be able to look at peoplePicker.test.ts.  I am trying to reach the code in the findAddressBook.then (it's the else there's no selectedGroup).  In order to do that I need to resolve kb.fetcher.nowOrWhenFetched function. I can't seem to use the existing mock in rdflib or create one of my own.  I have tried creating a jest.fn, I have tried jest.Mock and jest.spyOn.  There are lots of comments in the code to explain what test I am working on and some points about it.
=> Wip widget tests

test/unit/widgets/peoplePicker.test.ts
Had to change callback to be a named function.
=> Changed callback to be named

examples/buttons/index.html
=> Refactor askName example to use async/await

src/acl/acl-control.ts, test/unit/acl/acl-control.test.ts, test/unit/acl/index.test.ts
I ended up going down a rabbithole on this one, but wanted to check in the code that I think is a useful addition to the code base.
=> acl-control cleanup

Documentation/developers/testing_README.md, __mocks__/rdflib.ts, jest.config.js, src/acl/acl.ts, src/acl/types.ts, test/custom-matchers/toContainGraph.ts, test/custom-matchers/toEqualGraph.ts, test/setup.ts, test/unit/acl/acl.mocks.ts, test/unit/acl/acl.test.ts, test/unit/acl/mocks/aclWithAllAgents.ttl, test/unit/acl/mocks/defaultAcl.ttl, test/unit/acl/mocks/defaultAclDuplicate.ttl, test/unit/acl/mocks/docAcl.ttl, test/unit/helpers/createAgentMapFromTurtle.ts, test/unit/helpers/createGraphFromTurtle.ts, test/unit/helpers/createGraphFromTurtleFile.ts, test/unit/helpers/getFileContent.ts, test/unit/helpers/loadTurtleFileIntoGraph.ts, test/unit/helpers/loadTurtleIntoGraph.ts
Some work that I started doing for cleaning up the ACL module. It is not complete, but I think it adds value to the code base.
I hope the added matchers are reasonable additions to the test suite.
=> Acl cleanup

src/acl/add-agent-buttons.ts, src/widgets/buttons.ts
had to override bogius livestore type errors to be able to commit
=> Add file upload option to attachmentList

src/authn/authn.ts
- Fix space escaping in file name, and
-  Fix missing dom param to widgets.errorMessageBlock
=> Two bugs: Fix space escaping in file name and  missing dom param

src/header/styleMap.ts
Add the hover over the menu items to match inrupt design style.
=> Header add hover style

src/authn/authn.ts
=> fix embarrassing typo

src/create/create.ts, src/matrix/matrix.ts
I tried to work arround the type errors that occured on master lately.
=> Type errors

.github/workflows/ci.yml, Documentation/forms-intro.html, package.json, src/acl/access-groups.ts, src/acl/acl-control.ts, src/acl/add-agent-buttons.ts, src/acl/styles.ts, src/authn/authn.ts
left over from the migration to main branch
=> base gh actions on main branch instead of master

src/acl/access-controller.ts
- Since `pod owner` with `Control` has been added to NSS there is no need to limit user options in building ACL's 
- removed false comment in file.acl that the acl applies to the included folders
Tested on a local multi-user NSS with pod owner.
=> remove alert and confirm from sharing-pane

src/authn/authn.ts
=> Cleanup proptery names for appContext

src/widgets/forms/autocomplete/autocompletePicker.ts, src/widgets/forms/autocomplete/language.ts, src/widgets/forms/autocomplete/publicData.ts, test/unit/widgets/forms/autocomplete/language.test.ts
Fix language preferences so that they always include the defaults after the use's choice.
Add a few tests
Responding to https://github.com/solid/solidos/issues/42
Needs more tests ...
=> Fix language preferences (langfix)

src/widgets/forms/autocomplete/autocompletePicker.ts, src/widgets/forms/autocomplete/language.ts, src/widgets/forms/autocomplete/publicData.ts, test/unit/widgets/forms/autocomplete/language.test.ts
Regarding the talked about typos in https://github.com/solid/solid-ui/issues/429
=> Fix typos; closes #429

src/authn/authn.ts
To fix https://github.com/solid/solid-ui/issues/439
=> fix(authn): workspace message white and file id error

src/authn/authn.ts
Closes https://github.com/solid/solid-ui/issues/443
=> Suggest the current host as an OIDC issuer

.web_base, src/chat/infinite.js, src/widgets/peoplePicker.js
This removed the PUT and leaves only a PATCH which should work.
=> Try to address https://github.com/solid/solid-ui/issues/441

Documentation/form-examples/test-form.js
With a little function addStoHTTP
=> Fix fetch to add an s to http

Documentation/talks/FormsTalk.html
=> more slides

src/widgets/forms.js
To fix https://github.com/solid/solid-ui/issues/453
=> Remove bogus error condition

src/style.js, src/widgets/forms.js, src/widgets/forms/basic.ts, src/widgets/forms/fieldParams.ts, test/unit/widgets/forms/basic.test.ts
A few fixes, mostly style fixes, including functional style change breakage.
=> Forms fixes

Documentation/form-examples/structures3.html, src/widgets/buttons.ts, src/widgets/forms.js
Here my code improvements for ui:Choice. Among others:
-> when one adds a new Node it will only be created if at least one of its fields is edited successfully. 
-> subForm is refresh -> it is deleted and rendered again (probably can be solved more elegant with using refresh() -> next iteration)
-> made sure it still works with all examples we have (when BlankNodes or missing labels)
=> improved ui:Choice code

Documentation/FormsReadme.md, README.md
Added an overview for Forms and a link to it in readme.
=> Form documentation

src/style_multiSelect.js, src/widgets/forms.js, src/widgets/multiSelect.js
added multiselect to ui:choice and fixed a bug.
=> Form choice multiple

src/tabs.ts
Display ellipse only when there are menu options available. 
tested lcoally.
=> tried to condition display of ellipse

Documentation/form-examples/UserRoles.html, src/widgets/forms.js
see https://github.com/SolidOS/solidos/issues/180
added also a test.
=> fix for multi-select bug

src/chat/dateFolder.js, src/chat/infinite.js
dateFolder.js add promise catch err.
see issue # 522
=> infinite chat issue #522

src/login/login.ts
https://github.com/SolidOS/solid-logic/issues/60
=> remove hash from redirectUrl

src/login/login.ts, test/unit/widgets/forms/fieldFunction.test.ts
Just cleaned up the lint errors.
=> removed unused vars for linting
